baseURL = "https://www.regradetres.com.br/"
title = "Regra de Três"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"
#uglyURLs = true
disableKinds = ["taxonomy", "taxonomyTerm"]
disableLiveReload = true
copyright = "Regra de Três Simples e Composta"            # default: author.name
# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"           # Default language to use
paginate = 3                                              
rssLimit = 20             # Limit Entry Count to Rss file 
disqusShortname = "regradetres"      # disqus_shortname
#googleAnalytics = "UA-63562677-1"      # UA-XXXXXXXX-X

[permalinks]
  	post = "/:filename.html"
	amp = "/:filename.html/amp" 

[languages.en]
	languageCode = "pt-BR"

[author]                  # essential                    
	name = "Jean Carlos Novaes"

[sitemap]                 # essential                     
	changefreq = "weekly"
	priority = 0.5
	filename = "sitemap.xml"

[[menu.main]]             # config your menu              
	name = "Home"
	weight = 1
	identifier = "home"
	url = "/"

[params]
	amp = true # enables amp features
    ampCdnRoot = "https://cdn.ampproject.org/" # defined base cdn root of the amp projects files
    ampRelease = "v0" # define amp release you want to use
    ampElementsVersion = "0.1" # define amp-elements version you want to use

    # define which amp-elements you are using globally, these elements will be included in every page
    ampElements = ["amp-iframe","amp-font","amp-ad","amp-analytics","amp-dynamic-css-classes","amp-fx-flying-carpet","amp-sidebar","amp-social-share","amp-sticky-ad"]

    themeColor = "#ff1d55" # define a theme color (this will colorize the android address-bar)

    adsensePublisher = "ca-pub-123456789" # required if you want to include google adsense
    googleAnalytics = "UA-63562677-1" # required if you want to use google analytics
    #appleItunesApp = "app-id=123456789, app-argument=app-name://link/to/app-content" # required if you want to add an app banner with iOS app
    ampManifest = "/amp-manifest.json" # required if you want to add the app-banner feature

    alternatePageName = "Regra de Três Simples e Composta" # alternative name for website structured data
    organizationLogo = "https://gohugohq.com/logo.png" # set organization logo for structured data
    organizationName = "Regra de Três Simples e Composta" # set organization name
    organizationAddress = "Pç. Candido Leones, 46540-000, Ibipitanga - BA" # set organization address

    socialProfiles = ["http://www.facebook.com/your-profile","http://instagram.com/yourProfile","http://www.linkedin.com/in/yourprofile","http://plus.google.com/your_profile"]  # for sameAs in organization's structured data

    publisherName = "Jean Carlos Novaes" # publisher used in article schema
    publisherLogo = "https://gohugo-amp.gohugohq.com/logo-publisher.png" # https://developers.google.com/search/docs/data-types/articles#logo-guidelines
    publisherLogoWidth = 600 # logo width
    publisherLogoHeight = 60 # logo height

	since = "2014"            # Site creation time 
	homeFullContent = false   # if false, show post summaries on home page. Othewise show full content.
	rssFullContent = true     # if false, Rss feed instead of the summary

	# site info (optional)
	logoTitle = "Regra de Três"        # default: the title value
	keywords = ["regra de três", "regra de três simples","regra de três e composta", "regra de três simples e composta"]
	description = "Regra de três é o processo destinado a resolver problemas que envolvam grandezas diretamente ou inversamente proporcionais."
	image = "image/regra-de-tres.jpg"

	# paginate of archives, tags and categories
	archive-paginate = 3

	# paginate style, default use numbered pagination links
	# if true, use original "Previous" and "Next" links.
	paginateOriginalStyle = true

	# The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
	dateFormatToUse = "02/01/2006"

	# show word count and read time ?
	moreMeta = true

	google_verification = ""  # Google_Verification         # 谷歌

	# Link custom CSS and JS assets
	#   (relative to /static/css and /static/js respectively)
	customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
	customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

	[params.publicCDN]        # load these files from public cdn
		enable = false
		jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'		
    	slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'    

	[params.social]                                       
		a-email = "mailto:publicidadenovaes at gmail dot com"
		c-twitter = "https://www.regradetres.com.br/"
		d-facebook = "https://www.regradetres.com.br/"
		f-google = "https://www.regradetres.com.br/"

	